---
- name: Create upstart config
  become: yes
  template:
    dest: "{{ kafka.upstart_conf }}"
    owner: root
    group: root
    mode: 0644
    src: kafka.conf.j2
  notify:
    - restart kafka
  when: not kafka.use_systemd

- name: Create systemd config
  become: yes
  template:
    dest: "{{ kafka.systemd_service }}"
    owner: root
    group: root
    mode: 0644
    src: kafka.service.j2
  notify:
    - restart kafka
  when: kafka.use_systemd

- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  when: kafka.use_systemd

- name: Create log4j.properties
  become: yes
  become_user: "{{ kafka.user }}"
  template:
    dest: "/home/{{ kafka.user }}/etc/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart kafka

- name: Create server.properties
  become: yes
  become_user: "{{ kafka.user }}"
  template:
    dest: "/home/{{ kafka.user }}/etc/server.properties"
    mode: 0640
    src: server.properties.j2
  notify:
    - restart kafka

- name: Ensure Kafka is running
  become: yes
  service:
    name: kafka
    state: started
    enabled: yes

- name: Wait for Kafka port
  wait_for:
    host: "{{ kafka.listner_ip }}"
    port: "{{ kafka.port }}"
    state: started
    timeout: 30
