---

- include: build.yml
  tags:
    - build

  ## no configuration.
- name: configure.yml
  shell: echo "" > /tmp/ansible-city.java.configure
  args:
    creates: /tmp/ansible-city.java.configure
  tags:
    - configure
