---

- name: Generate aws vars
  template:
    src: "{{ deploy_vars_template_path | default('vars/deploy/deploy.yaml.template') }}"
    dest: "{{ deploy_vars_path | default('vars/deploy/deploy.yaml') }}"
    backup: true