---

- name: Setup environment variables
  become: yes
  template:
    src: elasticsearch.default.j2
    dest: /etc/default/elasticsearch
    backup: true
  notify:
    - restart elasticsearch

- name: Raise open file limits for elasticsearch and allow memory locking
  become: yes
  copy:
    src: 10-elasticsearch.conf
    dest: /etc/security/limits.d/10-elasticsearch.conf
    backup: yes
  notify:
    - restart elasticsearch
    
- name: Configure elasticsearch
  become: yes
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    backup: true
  notify:
    - restart elasticsearch

- name: Ensure Elasticsearch service is started
  become: yes
  service:
    name: elasticsearch
    state: started
