---
- name: Download logstash
  get_url:
    url: https://download.elastic.co/logstash/logstash/packages/debian/logstash-2.4.0_all.deb
    dest: /tmp/

- name: install logstash
  become: yes
  shell: dpkg -i /tmp/logstash-2.4.0_all.deb

- name: Install logstash plugins
  become: yes
  shell: "bin/plugin install {{ item }}"
  args:
    chdir: "/opt/logstash"
  with_items: logstash.plugins
  notify:
    - restart logstash

- name: Update logstash plugins
  become: yes
  shell: "bin/plugin update --no-verify {{ item }}"
  args:
    chdir: "/opt/logstash"
  with_items: logstash.plugins_update
  notify:
    - restart logstash

- name: Enable logstash service
  become: yes
  service:
    name: logstash
    enabled: yes
  notify:
    - start logstash
