#- name: Create upstart config
#  become: yes
#  template:
#    dest: "{{ kafka_manager.upstart_conf }}"
#    owner: root
#    group: root
#    mode: 0644
#    src: kafka_manager.conf.j2
#  notify:
#    - restart kafka_manager

#- name: Ensure Kafka Manager is running
#  become: yes
#  service:
#    name: kafka_manager
#    state: started
#    enabled: yes


#- name: Running kafka manager application
#  shell: nohup /root/bi6-1.0-SNAPSHOT/bin/kafka-manager -Dconfig.file=/path/to/application.conf -Dhttp.port={{ kafka_manager.port }} > /dev/null 2>&1 &
#  environment: "{{ kafka_manager.env_vars }}"

#- name: Wait for Kafka port
#  wait_for:
#    port: "{{ kafka_manager.port }}"
#    state: started
#    timeout: 30