- name: Create application config
  template:
    dest: /home/{{ kafka_manager.user }}/etc/application.conf
    owner: root
    group: root
    mode: 0644
    src: application.conf.j2


#- name: Running kafka manager application
#  shell: nohup /home/{{ kafka_manager.user }}/kafka-manager/bin/kafka-manager -Dconfig.file=/home/{{ kafka_manager.user }}/etc/application.conf -Dhttp.port={{ kafka_manager.port }} > /dev/null 2>&1 &
#  environment: "{{ kafka_manager.env_vars }}"

- name: Copy kafka manager upstart config
  template:
    src: kafka-manager.conf.j2
    dest: /home/{{ kafka_manager.user }}/etc/application.conf
    owner: root
    group: root
    mode: 0644
  notify: start kafka-manager



- name: Wait for Kafka Manager port
  wait_for:
    port: "{{ kafka_manager.port }}"
    state: started
    timeout: 30