- name: Create upstart config
  become: yes
  template:
    dest: "{{ kafka_manager.upstart_conf }}"
    owner: root
    group: root
    mode: 0644
    src: kafka_manager.conf.j2
  notify:
    - restart kafka_manager

#- name: Create kafka manager properties
#  become: yes
#  become_user: "{{ kafka.user }}"
#  template:
#    dest: "/home/{{ kafka.user }}/etc/server.properties"
#    mode: 0640
#    src: server.properties.j2
#  notify:
#    - restart kafka


#- name: Running web application
#  shell: nohup /root/bi6-1.0-SNAPSHOT/bin/bi6 -Dconfig.resource="production.conf" -DBYPASS_TWO_FACTOR_AUTH=true > /dev/null 2>&1 &
#  environment: "{{ env_vars }}"


#- name: Ensure Kafka Manager is running
#  become: yes
#  service:
#    name: kafka_manager
#    state: started
#    enabled: yes

#- name: Wait for Kafka port
#  wait_for:
#    port: "{{ kafka_manager.port }}"
#    state: started
#    timeout: 30