#- name: Create upstart config
#  become: yes
#  template:
#    dest: "{{ kafka_manager.upstart_conf }}"
#    owner: root
#    group: root
#    mode: 0644
#    src: kafka_manager.conf.j2
#  notify:
#    - restart kafka_manager

#- name: Ensure Kafka Manager is running
#  become: yes
#  service:
#    name: kafka_manager
#    state: started
#    enabled: yes


- name: Create application config
  template:
    dest: /home/{{ kafka_manager.user }}/etc/application.conf
    owner: root
    group: root
    mode: 0644
    src: application.conf.j2


- name: Running kafka manager application
  shell: nohup /home/{{ kafka_manager.user }}/kafka-manager/bin/kafka-manager -Dconfig.file=/home/{{ kafka_manager.user }}/etc/application.conf -Dhttp.port={{ kafka_manager.port }} > /dev/null 2>&1 &
  environment: "{{ kafka_manager.env_vars }}"

- name: Wait for Kafka Manager port
  wait_for:
    port: "{{ kafka_manager.port }}"
    state: started
    timeout: 30